### ISSUE TITLE
Effort towards supporting py3

### ISSUE THREAD

**Issue by zimmerle** [libinjection/python3-libinjection#1]
Having libinjection/libinjection#8 merged here.

**Comment by fzipi** [comment]
Added #2 .

**Comment by fzipi** [comment]
Do we need anything else? Or we can close this one?

I guess we can work on GHA build now.

**Comment by oxr463** [comment]
@zimmerle @fzipi is this ready to close?

**Comment by fzipi** [comment]
Yes.

**Comment by fzipi** [comment]
Can't close this one, sadly
